language: java
jdk:
  - oraclejdk8
notifications:
  email:
    recipients:
      - wollekuel@justeazy.de
    on_success: never
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#jmdflib"
    on_success: always
    on_failure: always